### ISSUE TITLE
[TODO] Implement building/packaging and testing RPMs

### ISSUE THREAD

**Issue by webknjaz** [ansible/pylibssh#90]
* [ ] Figure out what to target and the build env
* [ ] Define test containers
* [ ] Integrate into tox+GHA

**Comment by webknjaz** [comment]
New pointers/questions:
1. 2.10+ only?
2. spec files + build: https://docs.fedoraproject.org/en-US/quick-docs/create-hello-world-rpm/ / https://rpm-packaging-guide.github.io/ / https://drive.google.com/file/d/1Bi5p-dRW_Q-qcMAr4_89VhnEoAGyxEZ6/view?usp=sharing
     * `rpmdev-newspec` will create a spec file
     * put things in the right directories, and run `rpmbuild -ba mypackage.spec`
3. using centos/fedora + [`mock`] as a build env?
   * UBI available:
     ```console
     $ podman run -it --rm -v `pwd`:/io --name ubi8 registry.access.redhat.com/ubi8/ubi bash
     ```
4. runtime deps: libssh, ansible?
5. build deps: python? libssh-dev?
6. test containers: centos/fedora/ubi?

[`mock`]: https://github.com/rpm-software-management/mock

**Comment by webknjaz** [comment]
@ganeshrn could you please document the requirements here? There's no clear/complete understanding of the target envs...

**Comment by webknjaz** [comment]
Based on the last call, the plan is:
1) [ ] Package RPM for Fedora
2) [ ] Package RPM for CentOS
3) [ ] Package RPM for RHEL8
4) [ ] Rely on Python 3 that the recent Ansible is linked against in these OSs
5) [ ] Wait for the new channel/repository to get created in Brew (Koji)

**Comment by webknjaz** [comment]
Requested adding `libssh-devel` to ubi8: https://bugzilla.redhat.com/show_bug.cgi?id=1954863.

UPD: this is not going to happen so I've applied a hack to install them from CentOS RPMs in the CI.

**Comment by webknjaz** [comment]
@pabelanger could you please help figure out the RHEL channel this is supposed to get in?

**Comment by webknjaz** [comment]
Side idea: figure out if we could use bindep to declare deps for building RPMs because they are only available in CI workflow files right now which is suboptimal.

Ref: https://rbtcollins.wordpress.com/2015/07/12/bootstrapping-developer-environments-for-openstack/ / https://github.com/rbtcollins/bindep / https://docs.opendev.org/opendev/bindep/latest/ / https://pypi.org/project/bindep/

How to install packages returned by bindep: https://jakobandersen.github.io/mod/compiling.html#quick-start + `ansible -m package`? / https://github.com/ansible/ansible-builder/blob/abb609ab127158d2536a3d74febec62fa89277ec/ansible_builder/steps.py#L78

Examples: https://github.com/openstack/openstack-ansible/blob/master/bindep.txt / https://gerrit.cesnet.cz/plugins/gitiles/github/openstack-infra/zuul/+/19f8d27fd8d8a02322d3a56f8e18403df527d855/bindep.txt / https://github.com/openstack/ansible-role-python_venv_build/blob/master/bindep.txt

Another idea: extract running rpmlint into tox (may depend on https://github.com/tox-dev/tox-bindep).

**Comment by webknjaz** [comment]
Extra unsolved question: do we need to build RPMs for custom archs (it's currently only set up for x86_64). I'd like this to be integrated but objectively having QEMU may be ridiculously slow.

**Comment by pabelanger** [comment]
> Side idea: figure out if we could use bindep to declare deps for building RPMs because they are only available in CI workflow files right now which is suboptimal.
> 
> Ref: [rbtcollins.wordpress.com/2015/07/12/bootstrapping-developer-environments-for-openstack](https://rbtcollins.wordpress.com/2015/07/12/bootstrapping-developer-environments-for-openstack/) / [rbtcollins/bindep](https://github.com/rbtcollins/bindep) / [docs.opendev.org/opendev/bindep/latest](https://docs.opendev.org/opendev/bindep/latest/) / [pypi.org/project/bindep](https://pypi.org/project/bindep/)
> 
> How to install packages returned by bindep: [jakobandersen.github.io/mod/compiling.html#quick-start](https://jakobandersen.github.io/mod/compiling.html#quick-start) + `ansible -m package`? / [ansible/ansible-builder@`abb609a`/ansible_builder/steps.py#L78](https://github.com/ansible/ansible-builder/blob/abb609ab127158d2536a3d74febec62fa89277ec/ansible_builder/steps.py#L78)
> 
> Examples: [https://github.com/openstack/openstack-ansible/blob/master/bindep.txt](https://github.com/openstack/openstack-ansible/blob/master/bindep.txt?rgh-link-date=2021-06-11T18%3A37%3A29Z) / [gerrit.cesnet.cz/plugins/gitiles/github/openstack-infra/zuul/+/19f8d27fd8d8a02322d3a56f8e18403df527d855/bindep.txt](https://gerrit.cesnet.cz/plugins/gitiles/github/openstack-infra/zuul/+/19f8d27fd8d8a02322d3a56f8e18403df527d855/bindep.txt) / [https://github.com/openstack/ansible-role-python_venv_build/blob/master/bindep.txt](https://github.com/openstack/ansible-role-python_venv_build/blob/master/bindep.txt?rgh-link-date=2021-06-11T18%3A37%3A29Z)
> 
> Another idea: extract running rpmlint into tox (may depend on [tox-dev/tox-bindep](https://github.com/tox-dev/tox-bindep)).

You'd do something like:  https://github.com/ansible-collections/ansible.netcommon/blob/main/bindep.txt#L10

Which we automatically pickup in our python-builder image (assemble script) when we build containers. We standardize on bindep.txt files in our Zuul CI, to make is easier for developers to distro level packages into jobs.

So adding something here, is possible.

**Comment by webknjaz** [comment]
> You'd do something like: [https://github.com/ansible-collections/ansible.netcommon/blob/main/bindep.txt#L10](https://github.com/ansible-collections/ansible.netcommon/blob/main/bindep.txt?rgh-link-date=2021-06-11T19%3A13%3A06Z#L10)
> 
> Which we automatically pickup in our python-builder image (assemble script) when we build containers. We standardize on bindep.txt files in our Zuul CI, to make is easier for developers to distro level packages into jobs.

I want that for this repo's in-tree automation specifically, not for Zuul. Meaning that the automation needs to learn how to install those things (possibly from within tox).

**Comment by pabelanger** [comment]
> > You'd do something like: [https://github.com/ansible-collections/ansible.netcommon/blob/main/bindep.txt#L10](https://github.com/ansible-collections/ansible.netcommon/blob/main/bindep.txt?rgh-link-date=2021-06-11T19%3A16%3A01Z#L10)
> > Which we automatically pickup in our python-builder image (assemble script) when we build containers. We standardize on bindep.txt files in our Zuul CI, to make is easier for developers to distro level packages into jobs.
> 
> I want that for this repo's in-tree automation specifically, not for Zuul. Meaning that the automation needs to learn how to install those things (possibly from within tox).

https://opendev.org/zuul/zuul-jobs/src/branch/master/roles/bindep is the ansible role we use to manage bindep files.

**Comment by webknjaz** [comment]
@Jakuje let's see if this can be closed or if there are any ideas to be salvaged from the thread before doing so...

**Comment by Jakuje** [comment]
I do not think there is anything left from this thread. I think existing matrix is covering where we want to have ansible running. Its still in question whether we might want to build against some different distros where ansible is supported, but I guess that would be different task.
