### ISSUE TITLE
[TODO] Set up Sphinx docs

### ISSUE THREAD

**Issue by webknjaz** [ansible/pylibssh#95]
* [x] Integrate Sphinx into tox and GHA
* [x] Integrate RTD (almost ready -- https://readthedocs.org/projects/ansible-pylibssh/, need @ganeshrn to resync the webhook @ https://readthedocs.org/dashboard/ansible-pylibssh/integrations/127409/)
* [x] Enable RTD build status reports on PRs
* [x] Integrate RTD link into the dist metadata
* [x] Check in the Sphinx skeleton using https://github.com/ansible-community/sphinx_ansible_theme
* [ ] Integrate https://github.com/sphinx-contrib/apidoc

**Comment by webknjaz** [comment]
@ganeshrn atm it is nearly impossible to have Sphinx extract docstrings from Cython @ RTD. So I'm postponing this for better times.
Right now, it's best to just add the docs via RST.
